GET http://localhost:4000/api/

###

GET http://localhost:4000/api/articles

###

GET http://localhost:4000/api/articles/14

###

DELETE http://localhost:4000/api/articles/15

###

PUT http://localhost:4000/api/articles/14
content-type: application/json

{
  "featured": true,
  "title": "Novo titulo",
  "url": "http://www.url.com.br",
  "image_url": "http://www.url.com.br/images/icon.png",
  "news_site": "http://www.url.com.br",
  "summary": "Nova mensagem",
  "published_at": "2021-12-04T22:56:18Z",
  "events": [
    {
      "id": 1,
      "provider": "event provider"
    }
  ],
  "launches": [
    {
      "id": 1,
      "provider": "launch provider"
    }
  ]
}


###

POST http://localhost:4000/api/articles
content-type: application/json

{
  "featured": true,
  "title": "",
  "url": "http://www.url.com.br",
  "image_url": "http://www.url.com.br/images/icon.png",
  "news_site": "http://www.url.com.br",
  "summary": "sum",
  "published_at": "2021-12-04T22:56:18Z",
  "events": [
    {
      "id": 1,
      "provider": "event provider"
    }
  ],
  "launches": [
    {
      "id": 1,
      "provider": "launch provider"
    }
  ]
}