GET http://localhost:4000/api/articles

###

GET http://localhost:4000/api/articles/1

###

DELETE http://localhost:4000/api/articles/2

###

POST http://localhost:4000/api/articles
content-type: application/json

{
    "id": 0,
    "featured": false,
    "title": "titulo",
    "url": "http://www.url.com.br",
    "imageUrl": "http://www.url.com.br/images/icon.png",
    "newsSite": "http://www.url.com.br",
    "summary": "mensagem",
    "publishedAt": "string",
    "launches": [
      {
        "id": 123,
        "provider": "provider launch"
      }
    ],
    "events": [
      {
        "id": 12,
        "provider": "provider event"
      }
    ]
  }
